version: '3'

services:
  php:
    build: .
    command: /root/.symfony5/bin/symfony serve --no-tls
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
